CC = gcc
CFLAGS= -Wall -g -DNDEBUG

all: ex1 ex2 ex3 ex4 pyr ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18 ex19 ex20 ex21

ex1: ex1.c
	$(CC) $(CFLAGS) -o ex1 ex1.c

ex2: ex2.c
	$(CC) $(CFLAGS) -o ex2 ex2.c

ex3: ex3.c
	$(CC) $(CFLAGS) -o ex3 ex3.c

ex4: ex4.c
	$(CC) $(CFLAGS) -o ex4 ex4.c

pyr: pyr.c
	$(CC) $(CFLAGS) -o pyr pyr.c

ex5: ex5.c
	$(CC) $(CFLAGS) -o ex5 ex5.c

ex6: ex6.c
	$(CC) $(CFLAGS) -o ex6 ex6.c

ex7: ex7.c
	$(CC) $(CFLAGS) -o ex7 ex7.c

ex8: ex8.c
	$(CC) $(CFLAGS) -o ex8 ex8.c

ex9: ex9.c
	$(CC) $(CFLAGS) -o ex9 ex9.c

ex10: ex10.c
	$(CC) $(CFLAGS) -o ex10 ex10.c

ex11: ex11.c
	$(CC) $(CFLAGS) -o ex11 ex11.c

ex12: ex12.c
	$(CC) $(CFLAGS) -o ex12 ex12.c

ex13: ex13.c
	$(CC) $(CFLAGS) -o ex13 ex13.c

ex14: ex14.c
	$(CC) $(CFLAGS) -o ex14 ex14.c

ex15: ex15.c
	$(CC) $(CFLAGS) -o ex15 ex15.c

ex16: ex16.c
	$(CC) $(CFLAGS) -o ex16 ex16.c

ex17: ex17.c
	$(CC) $(CFLAGS) -o ex17 ex17.c

ex18: ex18.c
	$(CC) $(CFLAGS) -o ex18 ex18.c

ex19: ex19.c
	$(CC) $(CFLAGS) -o ex19 ex19.c

ex20: ex20.c
	$(CC) $(CFLAGS) -o ex20 ex20.c

ex21: ex21.c
	$(CC) $(CFLAGS) -o ex21 ex21.c

clean:
	rm -f ex1 ex2 ex3 ex4 pyr ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18 ex19 ex20 ex21
	rm -rf ex1.dSYM ex2.dSYM ex3.dSYM ex4.dSYM pyr.dSYM ex5.dSYM ex6.dSYM ex7.dSYM ex8.dSYM ex9.dSYM ex10.dSYM ex11.dSYM ex12.dSYM ex13.dSYM ex14.dSYM ex15.dSYM ex16.dSYM ex17.dSYM ex18.dSYM ex19.dSYM ex20.dSYM ex21.dSYM

rebuild:
	clean all
